name: Deploy-To-ACR

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 20.8.1

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        id: increment-git-tag
        run: |
          npx semantic-release
          echo "githubToken=${{ secrets.RELEASE_GITHUB_TOKEN }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      # - name: Login to Azure Container Registry
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.ACR_LOGIN_SERVER }}
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: 'Build, tag, and push image to Azure Container Registry'
      #   env:
      #     ACR_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
      #     ACR_REPOSITORY: ${{ secrets.ACR_REPOSITORY }}
      #   id: build-image
      #   run: |
      #     IMAGE_TAG=$(git describe --abbrev=0 --tags)
      #     echo "ACR_REGISTRY: $ACR_REGISTRY"
      #     echo "ACR_REPOSITORY: $ACR_REPOSITORY"
      #     echo "IMAGE_TAG: $IMAGE_TAG"
      #     TAG=$ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
      #     echo "image=$TAG" >> $GITHUB_ENV
      #     echo "image=$ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      #     docker build -t $TAG .
      #     docker push $TAG
      #   working-directory: '${{ github.workspace }}'
